name: Goal-app-build-ECR-image-deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Docker CLI & AWS CLI (only for local run)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg \
            lsb-release
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io awscli

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Docker image tag
        id: vars
        run: |
          echo "IMAGE_TAG=latest-$(echo ${GITHUB_SHA} | cut -c1-5)" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ env.IMAGE_TAG }}"

      - name: Build Docker Image
        run: |
            IMAGE_NAME="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/goal-app-frontend:${{ env.IMAGE_TAG }}"
            docker build --no-cache -t "$IMAGE_NAME" .
            docker save ${IMAGE_NAME} -o ./"$IMAGE_NAME.tar"
            echo "Built Docker image: $IMAGE_NAME"
            docker images  # List images to confirm

      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: "${IMAGE_TAG}.tar"

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Load and Push Docker Image
        run: |
          IMAGE_NAME="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/goal-app-frontend:${{ env.IMAGE_TAG }}"
          docker load -i "${IMAGE_TAG}.tar"
          # docker tag "${IMAGE_TAG}":latest my-dockerhub-username/"${IMAGE_TAG}.tar":latest/
          docker images

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Set Docker image tag
        id: vars
        run: |
          echo "IMAGE_TAG=latest-$(echo ${GITHUB_SHA} | cut -c1-5)" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ env.IMAGE_TAG }}"
      
      
        # Push the Docker image to Amazon ECR
      - name: Push Docker Image
        run: |
          docker images  # List images to confirm
          IMAGE_NAME="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/goal-app-frontend:${{ env.IMAGE_TAG }}"
          echo "Pushing image: $IMAGE_NAME"
          docker push "$IMAGE_NAME"

  update_deployment:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Update the Kubernetes deployment YAML with the new image tag
      - name: Update Kubernetes Deployment YAML
        run: |
          cat ./argocd_deployment/deployment.yaml
          sed -i "s|image: .*goal-app-frontend:.*|image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/goal-app-frontend:${{ env.IMAGE_TAG }}|g" ./argocd_deployment/deployment.yaml
          cat ./argocd_deployment/deployment.yaml

      # Commit the updated YAML file back to the repository
      - name: Commit updated Kubernetes YAML
        run: |
          git config --local user.name "Abir-K"
          git config --local user.email "abirbeatz@gmail.com"
          git add ./argocd_deployment/deployment.yaml
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
          git push https://${{ secrets.GH_PAT }}@github.com/Abir-K/goal-frontend-with-jenkins
